// Biblioteca dos 16 tipos — conteúdo original em português, tom Jornada Extraordinária.
// Estrutura por tipo: apelido, titulo, visao[], fortes[], atencao[], casal[].
const TYPES = {
ISTJ:{apelido:"O Inspetor",titulo:"Responsável e confiável",
visao:["Você é prático, metódico e leva a sério seus compromissos. Confia naquilo que já foi testado, organiza a vida com clareza e cumpre o que promete. As pessoas sabem que podem contar com você.",
"Valoriza ordem, tradição e responsabilidade. Prefere fatos concretos a especulações e gosta de saber exatamente o que se espera de você para então entregar com consistência."],
fortes:["Confiável: cumpre o que assume, mesmo quando é difícil.","Organizado: estrutura a vida e o trabalho com método.","Leal: dedicado à família e aos compromissos de longo prazo.","Prático: foca no que funciona e resolve com objetividade.","Estável: oferece segurança e constância a quem está perto."],
atencao:["Pode resistir a mudanças e a formas novas de fazer as coisas.","Às vezes parece rígido ou crítico com quem age diferente.","Pode priorizar a tarefa e esquecer de expressar afeto.","Tende a guardar para si o que sente."],
casal:["No casamento, você demonstra amor pela constância: presença, provisão e cuidado prático no dia a dia. Seu cônjuge encontra em você um porto seguro.","O crescimento vem ao verbalizar mais o afeto e ao abrir espaço para a espontaneidade do outro, lembrando que nem tudo precisa seguir um plano para dar certo."]},
ISFJ:{apelido:"O Protetor",titulo:"Dedicado e atencioso",
visao:["Você cuida das pessoas com lealdade e atenção aos detalhes. Percebe necessidades que passam despercebidas e age para que todos se sintam acolhidos e seguros.",
"Discreto e prático, valoriza harmonia, tradição e relações estáveis. Sua bondade é silenciosa, mas constante."],
fortes:["Cuidadoso: atento às necessidades concretas das pessoas.","Leal: dedicado e presente nos vínculos importantes.","Responsável: confiável nas grandes e pequenas coisas.","Caloroso: cria ambientes seguros e acolhedores.","Detalhista: lembra do que importa para quem ama."],
atencao:["Pode se sobrecarregar por dizer 'sim' a tudo.","Tende a guardar mágoas em vez de expressá-las.","Resiste a mudanças e a sair da zona de conforto.","Pode se esquecer das próprias necessidades."],
casal:["No casamento, seu amor aparece no servir diário e na atenção fiel ao bem-estar do cônjuge. Você constrói um lar onde o outro se sente cuidado.","O crescimento vem ao comunicar suas próprias necessidades e ao não carregar sozinho o peso de manter tudo em ordem."]},
INFJ:{apelido:"O Conselheiro",titulo:"Idealista e perceptivo",
visao:["Você busca propósito e significado em tudo. Tem uma intuição rara sobre as pessoas e enxerga possibilidades de crescimento onde outros não veem.",
"Reservado, mas profundo, valoriza autenticidade e harmonia. Une idealismo e determinação para servir a algo maior do que você mesmo."],
fortes:["Perceptivo: entende as pessoas em profundidade.","Idealista: movido por valores e propósito.","Determinado: persistente naquilo em que acredita.","Empático: sintoniza com o que o outro sente.","Inspirador: ajuda as pessoas a crescer."],
atencao:["Pode ser perfeccionista e exigente consigo mesmo.","Tende a se isolar quando sobrecarregado.","Guarda sentimentos profundos que poucos acessam.","Pode esperar demais dos outros e de si."],
casal:["No casamento, você oferece presença profunda, escuta e um desejo sincero de ver o cônjuge florescer. Busca uma união de almas, não apenas de rotina.","O crescimento vem ao aceitar o outro como ele é, sem o peso do ideal, e ao compartilhar seu mundo interior em vez de protegê-lo."]},
INTJ:{apelido:"O Estrategista",titulo:"Independente e visionário",
visao:["Você pensa em sistemas e planeja a longo prazo com lógica. Enxerga o quadro maior, antecipa consequências e busca eficiência e melhoria contínua.",
"Independente e exigente, confia na própria análise. Valoriza competência, conhecimento e autonomia."],
fortes:["Estratégico: planeja com visão de longo prazo.","Analítico: decide com lógica e clareza.","Independente: pensa por conta própria.","Determinado: persegue objetivos com foco.","Competente: busca domínio e excelência."],
atencao:["Pode parecer distante ou crítico nas relações.","Subestima a importância das emoções na decisão.","Tende a impor padrões altos aos que estão perto.","Resiste a expressar vulnerabilidade."],
casal:["No casamento, você demonstra amor com lealdade, compromisso e ações concretas para construir um futuro sólido com o cônjuge.","O crescimento vem ao dar espaço para a emoção e a espontaneidade, e ao lembrar que o relacionamento não é um projeto a otimizar, mas um vínculo a nutrir."]},
ISTP:{apelido:"O Artesão",titulo:"Prático e analítico",
visao:["Você resolve problemas com calma e gosta de entender como as coisas funcionam. Aprende fazendo e mantém a cabeça fria sob pressão.",
"Independente e observador, valoriza liberdade e eficiência. Age no momento certo, sem alarde."],
fortes:["Prático: resolve problemas com objetividade.","Calmo: mantém a serenidade em crises.","Habilidoso: aprende fazendo e domina o concreto.","Flexível: adapta-se às circunstâncias.","Lógico: analisa com clareza e bom senso."],
atencao:["Pode evitar conversas emocionais.","Tende a guardar sentimentos e parecer distante.","Resiste a compromissos que limitam a liberdade.","Pode adiar o diálogo sobre o relacionamento."],
casal:["No casamento, você demonstra amor resolvendo, consertando e estando presente de forma prática quando o cônjuge precisa.","O crescimento vem ao se abrir emocionalmente e ao investir tempo intencional na conexão, não só na solução de problemas."]},
ISFP:{apelido:"O Artista",titulo:"Sensível e gentil",
visao:["Você vive o presente e valoriza beleza, liberdade e harmonia. Sensível e gentil, demonstra cuidado por gestos mais do que por palavras.",
"Discreto e autêntico, segue seus valores com firmeza tranquila. Evita conflito e busca leveza."],
fortes:["Sensível: percebe e respeita os sentimentos do outro.","Gentil: cria um clima de paz e cuidado.","Autêntico: fiel aos próprios valores.","Presente: aproveita e valoriza o agora.","Flexível: adapta-se com naturalidade."],
atencao:["Evita conflitos mesmo quando o diálogo é necessário.","Guarda mágoas em silêncio.","Pode ter dificuldade com planejamento de longo prazo.","Tende a se subestimar."],
casal:["No casamento, você ama por gestos de carinho, presença e atenção delicada ao bem-estar do cônjuge.","O crescimento vem ao enfrentar conversas difíceis em vez de evitá-las, e ao expressar em palavras o que você sente."]},
INFP:{apelido:"O Mediador",titulo:"Idealista e leal aos valores",
visao:["Você busca autenticidade e significado profundo. Leal aos seus valores, sonha com um mundo melhor e cuida das pessoas com sensibilidade.",
"Reservado e imaginativo, valoriza harmonia e propósito. Por dentro, há um idealismo intenso e uma vida emocional rica."],
fortes:["Empático: compreende profundamente o outro.","Idealista: movido por valores e significado.","Leal: dedicado a quem e ao que ama.","Criativo: enxerga possibilidades e sentido.","Acolhedor: cria espaço seguro para o outro ser quem é."],
atencao:["Pode evitar conflito e adiar decisões difíceis.","Tende a idealizar e se frustrar com a realidade.","Guarda sentimentos intensos sem expressá-los.","Pode se cobrar demais e se isolar."],
casal:["No casamento, você oferece amor profundo, aceitação e o desejo de uma conexão verdadeira e significativa com o cônjuge.","O crescimento vem ao trazer o ideal para o chão da realidade e ao comunicar necessidades em vez de guardá-las."]},
INTP:{apelido:"O Pensador",titulo:"Curioso e lógico",
visao:["Você ama ideias, teorias e a busca pela verdade e coerência. Analisa tudo com curiosidade e independência, procurando entender em profundidade.",
"Reservado e original, valoriza lógica e autonomia intelectual. Questiona suposições e busca clareza."],
fortes:["Analítico: pensa com profundidade e lógica.","Curioso: busca entender como tudo funciona.","Original: enxerga soluções fora do óbvio.","Independente: forma as próprias conclusões.","Honesto: valoriza a verdade e a coerência."],
atencao:["Pode parecer distante ou abstrato nas relações.","Subestima o lado emocional das decisões.","Tende a postergar o que é prático.","Resiste a expressar afeto verbalmente."],
casal:["No casamento, você demonstra amor com lealdade, respeito intelectual e disposição para entender o ponto de vista do cônjuge.","O crescimento vem ao dar atenção ao mundo emocional do relacionamento e ao traduzir o que pensa em gestos concretos de cuidado."]},
ESTP:{apelido:"O Realizador",titulo:"Energético e direto",
visao:["Você age rápido e gosta de desafios práticos e do aqui-e-agora. Resolve no calor do momento, com energia e jogo de cintura.",
"Sociável e realista, valoriza ação, resultado e liberdade. Aprende fazendo e contagia com seu entusiasmo."],
fortes:["Energético: traz vida e ação ao ambiente.","Prático: resolve problemas no momento.","Sociável: conecta-se com facilidade.","Corajoso: encara desafios sem hesitar.","Adaptável: prospera na mudança."],
atencao:["Pode agir por impulso, sem pensar no longo prazo.","Tende a evitar conversas profundas.","Impaciente com rotina e detalhes.","Pode minimizar o lado emocional."],
casal:["No casamento, você ama com presença ativa, aventura e disposição para resolver o que for preciso pelo cônjuge.","O crescimento vem ao desacelerar para conversas profundas e ao considerar o impacto de longo prazo das decisões a dois."]},
ESFP:{apelido:"O Animador",titulo:"Espontâneo e caloroso",
visao:["Você contagia com entusiasmo e valoriza experiências e pessoas. Vive o presente com alegria e leva leveza a quem está por perto.",
"Sociável e caloroso, valoriza harmonia e diversão. Demonstra afeto com generosidade e presença."],
fortes:["Caloroso: acolhe e anima as pessoas.","Espontâneo: traz alegria e leveza.","Generoso: cuida com presença e gestos.","Sociável: cria conexões com facilidade.","Presente: aproveita e celebra o agora."],
atencao:["Pode evitar conflitos e temas difíceis.","Tende a adiar planejamento de longo prazo.","Sensível à crítica.","Pode se dispersar em meio a estímulos."],
casal:["No casamento, você ama com afeto demonstrado, alegria compartilhada e atenção generosa ao cônjuge.","O crescimento vem ao encarar conversas sérias quando necessário e ao equilibrar espontaneidade com planejamento conjunto."]},
ENFP:{apelido:"O Inspirador",titulo:"Entusiasta e criativo",
visao:["Você vê possibilidades em tudo e conecta pessoas e ideias. Entusiasta e criativo, inspira quem está por perto a sonhar e crescer.",
"Caloroso e imaginativo, valoriza autenticidade, liberdade e relações significativas. Sua energia abre portas."],
fortes:["Entusiasta: inspira e mobiliza as pessoas.","Criativo: enxerga possibilidades e conexões.","Empático: sintoniza com o outro.","Caloroso: cria vínculos verdadeiros.","Adaptável: abraça o novo com facilidade."],
atencao:["Pode dispersar a energia em muitas frentes.","Dificuldade com rotina e acompanhamento de detalhes.","Sensível a conflito e crítica.","Tende a idealizar e se frustrar."],
casal:["No casamento, você ama com paixão, incentivo e o desejo de crescer junto com o cônjuge rumo a algo maior.","O crescimento vem ao sustentar o compromisso na rotina e ao aceitar o cônjuge como ele é, sem o peso do ideal."]},
ENTP:{apelido:"O Inovador",titulo:"Engenhoso e questionador",
visao:["Você adora debater, explorar possibilidades e desafiar o status quo. Engenhoso e rápido, gera ideias e enxerga ângulos que outros não percebem.",
"Sociável e curioso, valoriza desafio intelectual e liberdade. Aprende discutindo e prospera no novo."],
fortes:["Engenhoso: resolve problemas com criatividade.","Articulado: comunica e convence com facilidade.","Curioso: explora ideias sem medo.","Energético: traz dinamismo aos projetos.","Flexível: adapta-se e improvisa bem."],
atencao:["Pode debater a ponto de gerar atrito.","Dificuldade com rotina e finalização.","Tende a racionalizar e minimizar emoções.","Resiste a regras e compromissos rígidos."],
casal:["No casamento, você ama com estímulo, parceria intelectual e disposição para crescer e inovar junto ao cônjuge.","O crescimento vem ao escolher a conexão acima do 'ter razão' no debate e ao dar atenção constante ao lado emocional do vínculo."]},
ESTJ:{apelido:"O Administrador",titulo:"Organizado e decidido",
visao:["Você gosta de liderar, estruturar e fazer as coisas acontecerem. Decidido e prático, organiza pessoas e recursos rumo a resultados claros.",
"Direto e responsável, valoriza ordem, compromisso e tradição. As pessoas sabem onde você está."],
fortes:["Organizado: estrutura e executa com eficiência.","Decidido: assume a liderança quando preciso.","Responsável: cumpre e cobra compromissos.","Leal: dedicado à família e às instituições.","Confiável: oferece estabilidade e direção."],
atencao:["Pode parecer controlador ou inflexível.","Tende a impor o próprio jeito de fazer.","Subestima a importância das emoções.","Pode priorizar tarefa acima de conexão."],
casal:["No casamento, você ama com provisão, compromisso firme e dedicação a construir um lar estável para o cônjuge.","O crescimento vem ao flexibilizar o controle, ao ouvir antes de decidir e ao expressar afeto além das responsabilidades."]},
ESFJ:{apelido:"O Anfitrião",titulo:"Cordial e cooperativo",
visao:["Você cuida do grupo e valoriza harmonia e compromissos sociais. Cordial e atento, faz todos se sentirem incluídos e cuidados.",
"Caloroso e responsável, valoriza tradição, lealdade e relações próximas. Servir é natural para você."],
fortes:["Cordial: acolhe e cuida das pessoas.","Cooperativo: constrói harmonia no grupo.","Responsável: confiável e dedicado.","Atencioso: lembra do que importa ao outro.","Leal: presente e fiel nos vínculos."],
atencao:["Pode depender demais da aprovação dos outros.","Evita conflito mesmo quando necessário.","Tende a se sobrecarregar servindo.","Sensível à crítica."],
casal:["No casamento, você ama com cuidado prático, atenção fiel e dedicação a um lar harmonioso para o cônjuge.","O crescimento vem ao expressar suas próprias necessidades e ao não medir o amor pela aprovação recebida."]},
ENFJ:{apelido:"O Mentor",titulo:"Carismático e empático",
visao:["Você inspira e desenvolve pessoas rumo a um bem comum. Caloroso, articulado e perceptivo, motiva os outros e enxerga o potencial de cada um.",
"Movido por valores e propósito, busca harmonia e impacto positivo. Lidera pelo exemplo e pelo cuidado genuíno."],
fortes:["Carismático: inspira e mobiliza as pessoas.","Empático: capta as necessidades do outro.","Dedicado: investe no crescimento de quem ama.","Confiável: cumpre o que promete.","Apaixonado: vive e defende seus valores."],
atencao:["Pode assumir os problemas do outro como seus.","Tende a pressionar pelo 'melhor' do cônjuge.","Leva conflito e rejeição para o lado pessoal.","Pode negligenciar as próprias necessidades."],
casal:["No casamento, você ama com entrega, incentivo e um cuidado profundo pelo florescimento do cônjuge. Busca uma união com propósito.","O crescimento vem ao encorajar sem pressionar, ao aceitar o tempo do outro e ao cuidar de si para não se esgotar no servir."]},
ENTJ:{apelido:"O Comandante",titulo:"Líder natural e estratégico",
visao:["Você organiza recursos e pessoas para atingir grandes metas. Líder natural e estratégico, decide com firmeza e enxerga o caminho à frente.",
"Direto e determinado, valoriza competência, eficiência e resultado. Assume a responsabilidade de fazer acontecer."],
fortes:["Estratégico: enxerga e planeja o caminho.","Decidido: lidera e assume responsabilidade.","Determinado: persegue metas com foco.","Articulado: comunica com clareza e força.","Competente: busca excelência e resultado."],
atencao:["Pode parecer dominador ou impaciente.","Subestima o impacto das emoções nas relações.","Tende a impor padrões altos ao cônjuge.","Pode priorizar metas acima da conexão."],
casal:["No casamento, você ama com compromisso firme, parceria e dedicação a construir um futuro sólido ao lado do cônjuge.","O crescimento vem ao suavizar o controle, ao ouvir com paciência e ao valorizar a conexão emocional tanto quanto os resultados."]}
};
const AXIS_LABELS = {
E:["Extroversão","Onde você busca energia: no mundo externo de pessoas e ação."],
I:["Introversão","Onde você busca energia: no mundo interno de ideias e reflexão."],
S:["Sensação","Como capta informação: por fatos concretos e detalhes."],
N:["Intuição","Como capta informação: por padrões, significados e possibilidades."],
T:["Pensamento","Como decide: pela lógica e análise objetiva."],
F:["Sentimento","Como decide: por valores e impacto nas pessoas."],
J:["Julgamento","Como lida com a vida: de forma planejada e organizada."],
P:["Percepção","Como lida com a vida: de forma flexível e espontânea."]
};
const CLARITY_LABEL = {1:"LEVE",2:"MODERADO",3:"CLARO",4:"MUITO CLARO"};
